language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/julianightlies -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - git config --global user.name "Travis User"
  - git config --global user.email "travis@example.net"
script:
  - julia -e 'versioninfo();Pkg.init();'
  - julia -e 'Pkg.add("Calculus");Pkg.add("Optim")'
  - mkdir -p ~/.julia/NLsolve
  - cp -R ./* ~/.julia/NLsolve/
  - julia ./test/runtests.jl
